docsPath: folder2
structure:
  readme: introduction.md
  summary: test.md
  assets: assets
shadowDocs: 
  - "spark/**.json"
  - "daccC/**/*.java"
  - "docs/aaa/**"
  - "bau"
footerTemplate: ""
headerIncludes: ""
